# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/


$(document).ready ->
  $('input.search-plant').on 'keyup change paste', (event) ->
    name = $(this).val()
    if name
      console.log 'Searching ' + name
      $.ajax
        url: '/plants/autocomplete/' + name
        type: 'POST'
        dataType: 'JSON'
        success: (e) ->
          console.log e.length
          if e.length > 0
            $('.search-results').removeClass 'hide'
            $('.search-results ul').html ''
            $.each e, (index, val) ->
              $('.search-results ul').append '<li><a href=\'/plants/' + val.id + '/\'>' + val.name + '</a></li>'
              return
          else
            $('.search-results').addClass 'hide'
            $('.search-results ul').html ''
          return
    return
  return

# ---
# generated by js2coffee 2.1.0